### PR TITLE
 - Updated api to be compatible with v16.1.1 api and should be backwa…

### PR DESCRIPTION
**Pull request by Michaellh0079**
…rds compatible with some previous versions.

### CODE REVIEW

**Comment by lindsleycj** [comment]
@Michaellh0079 I was just looking at the latest cumulus-api docs. Should a `replace_rule` and `replace_granule` be added.

https://nasa.github.io/cumulus-api/v18.1.0/#cumulus-api

It's mentioned in the v18.1.0 release notes.

I just made a change in my forked repo:  https://github.com/lindsleycj/cumulus-api/tree/feature/cxl-cumulus18

But since I use Ruff for auto-formatting it made a number of other changes.  What do you all use for formatting and I'll change my vscode workspace to use that to change things back.

**Comment by Michaellh0079** [comment]
@lindsleycj [replace_granule](https://github.com/ghrcdaac/cumulus-api/blob/mlh0079-5576-cumulus-16/cumulus_api/main.py#L388)

I will update with replace rule.

**Comment by lindsleycj** [comment]
Just to confirm, per the API docs, there should be `replace_granule`, `update_granule`, `replace_rule` and `update_rule`.  Is that what you were planning to do?

I won't make my own PR.  If you do look at my branch, you'll see that I updated the CHANGELOG plus the `version.py` and `setup.py`. Do you think those should be updated each time a new release is created?

**Comment by Michaellh0079** [comment]
@lindsleycj They should all be present now with the correct verbs:
 - replace_granule: https://github.com/ghrcdaac/cumulus-api/blob/mlh0079-5576-cumulus-16/cumulus_api/main.py#L388
 - update_granule: https://github.com/ghrcdaac/cumulus-api/blob/mlh0079-5576-cumulus-16/cumulus_api/main.py#L315
 - replace_rule: https://github.com/ghrcdaac/cumulus-api/blob/mlh0079-5576-cumulus-16/cumulus_api/main.py#L502
 - update_rule: https://github.com/ghrcdaac/cumulus-api/blob/mlh0079-5576-cumulus-16/cumulus_api/main.py#L492

**Comment by lindsleycj** [comment]
Looks great!  Thanks so much.

**Review by camposeddie — APPROVED** [review]

**Pull request merged**
